### ISSUE TITLE
POP_OS 20.10

### ISSUE THREAD

**Issue by xblahoud** [aidenfoxx/wsl2-popos#1]
Thank you very much for this repo. Can I reuse it for Pop_OS 20.10? How can I create the exported file?

**Comment by aidenfoxx** [comment]
You're more than welcome to fork the repo!

The simplest way to upgrade would be to boot the provided export, upgrade to 20.10, then re-export the image using `wsl.exe --export popos <ExportName>`.

As for creating an image from scratch: that requires you to create a new WSL instance based on the pop_os filesystem image from the live iso. You can then manually configure things to play nice with WSL (check "config/.bashrc").

This guide seems to broadly match the steps I took: https://gist.github.com/artman41/858450e2c29b239d8692213b684ada25

EDIT: I forgot to mention, GNOME doesn't work well without systemd. To get this working, I compiled a systemd shim for WSL called genie (https://github.com/arkane-systems/genie) inside the WSL instance, which is triggered in  `.bashrc` to initialize gnome with systemd.

**Comment by xblahoud** [comment]
Thanks!

I've tried to make a new image, but failed. The reason for the failure was that there is currently no support for Ubuntu/Pop 20.10 in Genie. A tried a few trials to make it work but I always failed, even with the latest release of Genie.

After two days of trials, I've decided to wait a bit and see if things evolve.

**Comment by milesbuckton** [comment]
Hi @xblahoud, I managed to upgrade the Pop!_OS 20.04 instance to 20.10, then I built genie [1.34](https://github.com/arkane-systems/genie/releases/tag/1.34) (changed the `systemd-timeout` setting to 5s), and finally altered the `.bashrc` genie commands slightly. After this I was able to run Pop!_OS 20.10! 😄👏 See below:

![image](https://user-images.githubusercontent.com/37063023/111074959-3a4ade00-84ee-11eb-9ac3-3c530184639f.png)

You can review my [fork](https://github.com/milesbuckton/wsl2-popos) for more details. It includes the WSL2 instance split into multiple volumes (due to the Github 100MB file size constraints)!

Thank you to @aidenfoxx for creating the base to make this all possible! ⭐I tried multiple times to get this right using the Ubuntu 20.04/20.10 base, but to no avail!

**Comment by aidenfoxx** [comment]
Nice! Good job man. Looks good to me, and if it works, it works.

I'm not gonna continue to support my repo since it was really just an experiment, but if you wanna keep it going, that's great. 😄

**Comment by milesbuckton** [comment]
Thank you @aidenfoxx...I couldn't have done it without you! 🤜🤛 You did some great work here, and kudos for putting it out there. 🏅 I'd like to keep it going - and I'll try to contribute to it when I get the chance. Hopefully I can upgrade the 20.10 base to 21.04 when it comes out. 😉

**Comment by milesbuckton** [comment]
ℹ️ One thing I found out after the fact was to change one of the `.bashrc` config settings to: `export LIBGL_ALWAYS_INDIRECT=0`.
This enables OpenGL support which does work. 😄 See the Graphics property below, and compare it with the one above:

![OpenGL](https://user-images.githubusercontent.com/37063023/111309402-84ee6680-8664-11eb-9e44-cf5a117fa42c.png)

💡 Bear in mind: this will need to be changed within the WSL2 instance `sudo nano ~/.bashrc`.

**Comment by aidenfoxx** [comment]
That works? When I set up the repo initially, I would get a black screen without setting `LIBGL_ALWAYS_INDIRECT=1`. Might be something that fixed itself with a later version of WSL. 🤷

**Comment by milesbuckton** [comment]
It does...can you believe it!? 😄I tried it with `Steam`. 😎

**Comment by xblahoud** [comment]
Hi @milesbuckton ! Thank you for taking up on this. I would be glad to test. I can't find any changes in your fork, not even in the 20.10 branch. I remember to see some changes a few days back when I just glimpsed. Did you remove it? Or it's just me being stupid?

**Comment by milesbuckton** [comment]
Hey @xblahoud, you're welcome. 😄 Sorry, it's not you being stupid - I did remove it temporarily. I wanted to align my origin `master` (fork) with the upstream `master`. The reason is the following:
1. I've created a feature branch called `20.10` where I'm still busy adding all the commits. (I should be done in the next 3 hours, or so.)
2. I want to see if I can squash the feature branch `20.10` commits into my origin `master` with a pull request (PR). I'll let you know once I'm done.

**Comment by xblahoud** [comment]
Hi @milesbuckton, thanks! I just picked a wrong time. I can wait when you are done, no problem. Good luck!

**Comment by milesbuckton** [comment]
Hi @xblahoud, OK - my idea 💡 worked - and it's done! 😎👏🏻 You'll notice that my origin `master` is only one commit ahead now. I deleted the feature branch `20.10`, as it's no longer needed. Please clone the repo, and test it. Let me know if it works for you. 😄

P.S. Try to switch on OpenGL (as described above) **after** you've tested that the non-OpenGL is working. 😉 GNOME performs much better with OpenGL turned on! 🚀

**Comment by xblahoud** [comment]
@milesbuckton, it works! Both the clean system and the OpenGL support. Thank you very much!

**Comment by milesbuckton** [comment]
It's my pleasure @xblahoud...I'm delighted that it all worked out in the end!🎆🙌🏻🍾🥂 Thank you for taking the time to test on your side! 😎 Enjoy. 🍸
